[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*
markers =
    courses: тесты для проверки страницы курсов
    regression: регрессионные тесты
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировка для тестов, связанных с авторизацией пользователей.